spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.seth.backend: DEBUG
app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000