spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.seth.backend: DEBUG
app:
  dev-admin:
    username: ${DEV_ADMIN_USERNAME:viseth@gmail.com}
    email: ${DEV_ADMIN_EMAIL:viseth@gmail.com}
    password: ${DEV_ADMIN_PASSWORD:Admin@123}
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000