import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Mesang High School",
  description: "Generated by Viseth",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}